services:
  web: 
    container_name: web_project_1
    image: node:25-alpine3.22
    working_dir: /app/web
    ports:
      - "5000:5173"
    volumes:
      - ./web:/app/web
    command: ["npm", "run", "dev","--", "--host"]
  api:
    container_name: api_project_1
    image : khanghoangvu/khangvu-project-01:001
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3010"
    volumes:
      - ./api:/app/api
    command: ["npm", "run", "dev"]
  db: 
    container_name: db_project_1
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data